# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RNVerloopSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VerloopSDKiOS', '~> 0.2'
  pod 'React'


  # Pods for RNVerloopSdk

end
